services:
  wiremock:
    image: wiremock/wiremock
    volumes:
      - ./wiremock:/home/wiremock
    ports:
      - "8080:8080"
  wiremock-ssl:
    image: wiremock/wiremock
    volumes:
      - ./wiremock:/home/wiremock
    command: [ "--https-port", "8443",
               "--disable-http",
               "--verbose" ]
    ports:
      - "8443:8443"
  wiremock-ssl-p12:
    image: wiremock/wiremock
    volumes:
      - ./wiremock:/home/wiremock
    command: [ "--https-port", "9443",
               "--disable-http",
               "--https-keystore", "/home/wiremock/wiremock.p12",
               "--keystore-type", "PKCS12",
               "--verbose" ]
    ports:
      - "9443:9443"

